---
- hosts: WebServer
  become: yes
  tasks:
  - name: Installing a Tomcat on RedHat Mechines
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
    tags:
      - install
  - name: Installing Tomacat on Ubuntu Mechines
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    tags:
      - install
      - service
  - name: Print free memory
    debug:
      msg: "Free memory is {{ ansible_memory_mb.real.free}}"
    tags:
      - debug
  - name: Start the Apache Service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
  - name: Copy the home Page
    template:
      src: Index.html.j2
      dest: /var/www/html/index.html
    notify: restart httpd
    handlers:
      - name: restart httpd
