---
- hosts: WebServer
  tasks:
  - name: Reading content from the file
    command: cat /etc/ansible/Ansible_Examples/Test
    register: cat_contents
  - name: Display the content 
    debug:
      msg: "{{cat_contents}}"